### ISSUE TITLE
Add to a package manager

### ISSUE THREAD

**Issue by rebelzach** [timeglass/glass#21]
Any thoughts about adding this to a package manager like Homebrew?

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

Certainly could help increase exposure and ease of install/updates.

**Comment by advdv** [comment]
I think this is a great idea, i'm gonna schedule this for the 1.0 release, we first need to focus on getting cross-platform and querying working. In the meantime maybe some comp-and-paste shell one-liners for a better installation experience? I'm gonna take a look at it.

**Comment by advdv** [comment]
I've created installers for windows and mac - I've went with a .pkg installer for now instead of homebrew.
