### ISSUE TITLE
Unable to get a timer to start

### ISSUE THREAD

**Issue by rebelzach** [timeglass/glass#37]
For what its worth, here is a bug I ran into and my steps to resolve

I noticed that glass was no longer inserting time into my commits. When running `glass status` I received `No timer appears to be running for '/Users/...': Daemon doesn't appears to be running.` 

I ran `glass start` and got the timer started message. However `glass status` yielded the same error. `glass stop` had no effect either

When I tried to start the daemon manually I received `It appears another Daemon is already running or a previous instance didn't shutdown properly, use -force to force start.` 

running `glass-daemon -force` and then terminating seems to have corrected the issue.

**Comment by advdv** [comment]
Thanks for reporting, I ran into the  issue myself and it will be fixed after pull request https://github.com/timeglass/glass/pull/35 is merged and released. It seems to occur when the daemon somehow didn't shutdown gracefully.

The correct way to fix it in the meantime is to restart the daemon manually using the -force flag as you mentioned.

**Comment by advdv** [comment]
Fixed in v0.5.2, [check it out!](https://github.com/timeglass/glass/releases/tag/v0.5.2)
