### ISSUE TITLE
Option to put duration in message body instead of title

### ISSUE THREAD

**Issue by tonglil** [timeglass/glass#42]
After using this for a few days, I feel like git messages become too cluttered with these time measurements.

I would like to keep the durations, but instead have them in the git message body.

This would also allow me to write longer commit messages.

**Comment by advdv** [comment]
Hey There! I'm not sure, but you should be able to prefix the message format with newlines like so:

```
"commit_message": "\n\n [spent {{.}}]"
```

The newlines should move it to the next line and effectively write it to the body of the message right?
