### ISSUE TITLE
timeglass.json in ~/

### ISSUE THREAD

**Issue by tonglil** [timeglass/glass#43]
Option to read `timeglass.json` from user's home folder as a `.timeglass.json` file.

**Comment by advdv** [comment]
Thanks for the feedback! Could you elaborate a bit on why you would like to see this option?

**Comment by tonglil** [comment]
Sure! I'm the only one on my team who uses it but I'd like to track the time in the commit message body so it seems optional (and therefore don't need that file in the repo).

**Comment by advdv** [comment]
Sorry for not getting back to you earlier, I see what you mean. The main issue I have is that it hard to facilitate cascading configuration. What if their is a config file in both the ~/ as well as the project directory? I would like to avoid such complexity until the project is more stable. I'm scheduling this for 1.0, in the meantime you can add it to your `.gitignore`?
