### ISSUE TITLE
Proposal: global configuration

### ISSUE THREAD

**Issue by mgaitan** [timeglass/glass#48]
the docs says I can customize the configuration by adding a file `timaglass.json` in the root of my git repo. This not only increase the pollution of boilerplate files but it's also very common that we want the same config in every repo we work on. 

For example, mine's is like this: 

``` json
{
    "mbu": "1m",
    "commit_message": "",
    "auto_push": false
}
```

so, should I copy&paste this file each time I start a new project? 

I propose a global editable file in `~/.config/timeglass/timeglass.json`. 
the priority should be 
1. local custom configuration 
2. global custom configuration
3. defaults.

**Comment by advdv** [comment]
Hey Martin, thanks for the feedback. I'm in the mids off rolling out a new version #41  (0.6.0), and since you're the second person  requesting this feature ( #43 ) i'll look into the possibility of including a global configuration.

**Comment by mgaitan** [comment]
cool, thanks

**Comment by advdv** [comment]
I rolled out a new release that includes a way of defining system wide default configuration, we won't be able to do this per user yet but hopefully that will be possible in the future. I hope you like it, and please try it out and let me know how it goes.
