### ISSUE TITLE
Add option to respect .gitignore file

### ISSUE THREAD

**Issue by rebelzach** [timeglass/glass#54]
I develop in Xamarin, which likes to store build files along side the project files, during a long build my timer won't pause. At this point, I don't think a separate ignore file is needed, I imagine most people want to track time for only the files that will ultimately be committed.

**Comment by advdv** [comment]
Immitating git's .gitignore behaviour is hard (I've tryed it in the past), instead I'm looking into tracking time on a per file basis. This involves comparing it with the actual files that are committed and in turn will only commit the time spent on files being tacked by Git. tldr; In the upcoming release (hopefully next weekend) .gitignored files will trigger timers but time spent on these files will not be committed.

**Comment by Mihailoff** [comment]
See #51
