### ISSUE TITLE
Brainstorm: Configuration

### ISSUE THREAD

**Issue by advdv** [timeglass/glass#7]
including configuring the minimal billable unit and ignoring certain directories. Discussion

**Comment by y9v** [comment]
i would like to have an option to modify the format of time information in the commit message

**Comment by advdv** [comment]
@lebedev-yury Thanks for the feedback, coming right up: https://github.com/timeglass/glass/pull/17, what do you think of configuring it like this: https://github.com/timeglass/glass/blob/0.5/docs/config.md

**Comment by y9v** [comment]
nice!

**Comment by rebelzach** [comment]
Will tampering with the message affect the ability to query? Is that info stored elsewhere?

**Comment by advdv** [comment]
Hey @rebelzach! Yes indeed, to counter this configuration will ship together with an implementation that stores actual time measurements using git-notes; a rather unkown Git feature but perfect for storing metadata alongside commits and gives will give us a decent separation of 'presentation' (augmenting commit messages) and storage (git-notes). notes do live in a separate branch that has to be pushed deliberately (or we automate it with yet another hook). 

The actual downside is that it makes Timeglass strongly dependant on Git and will make it harder to port it to other version control systems in the future: hg, sub etc

What do you think?

**Comment by rebelzach** [comment]
I'm no expert, but it makes sense to me to try to get "feature complete" on git and try to break out the git dependencies as much as possible (i.e. Adapters, actors, etc). Git continues to grow to handle submodules and large files better, I think its a great place to start. I would hope this project will attract more contributors in the long run. Contributors that could help with other CVS support

**Comment by rebelzach** [comment]
I'd also like the ability to format the time output not sure if there is an easy way to use the `go` formatter for this. https://pauladamsmith.com/blog/2011/05/go_time.html

**Comment by advdv** [comment]
Do you mean for the commit message right? Go templating allows you to do the following in the configuration file as an example:

```
"commit_message": " [spent {{printf \"%0.1f\" .Hours}} hours]",
```

will output the following message "[spent 0.1 hours]"

**Comment by rebelzach** [comment]
:+1: Awesome thanks for the info.
